issuer: http://localhost:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

telemetry:
  http: 0.0.0.0:5558

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: axon
    redirectURIs:
      - "https://localhost:5000/api/v1/auth/callback"
    name: "Axon"
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0

enablePasswordDB: true

staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$12$JQhJRbvzcLxjGUx33I8oNePtRqWPlkIHkM/yO4GPBoylFU6EJASKy" # password is "password"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
    groups:
      - "admin"
      - "users"
  - email: "user@example.com"
    hash: "$2a$12$JQhJRbvzcLxjGUx33I8oNePtRqWPlkIHkM/yO4GPBoylFU6EJASKy" # password is "password"
    username: "user"
    userID: "a169451c-8525-4367-9cfe-31c2ce647c61"
    groups:
      - "users"
