# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: ^charts/.*templates/
      - id: end-of-file-fixer
        exclude: ^web/src/auto-imports\.d\.ts$
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles
        description: Runs hadolint Docker image to lint Dockerfiles
        language: docker_image
        types: ["dockerfile"]
        entry: ghcr.io/hadolint/hadolint hadolint

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      - id: go-mod-tidy
      - id: go-fmt
      - id: go-build-repo-mod
      - id: golangci-lint-mod
        args: [--fix]
      - id: go-test-mod

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.0.0a2
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, postgres, --exclude-rules, "RF06,RF04"]
      - id: sqlfluff-fix
        args: [--dialect, postgres, --exclude-rules, "RF06,RF04"]

  - repo: local
    hooks:
      - id: eslint-web
        name: ESLint Web
        entry: bash -c 'cd web && pnpm exec eslint .'
        language: system
        pass_filenames: false

      - id: build-web
        name: Build Web
        entry: bash -c 'cd web && pnpm run build'
        language: system
        pass_filenames: false
